name: phantom

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    env:
      BUILD_TYPE: Release

    steps:
    - name: "Preparation"
      uses: actions/checkout@v4

    - name: "1/7: Clone (JUCE)"
      uses: actions/checkout@v4
      with:
        repository: juce-framework/JUCE
        ref: 2f980209cc4091a4490bb1bafc5d530f16834e58
        path: ${{runner.workspace}}/phantom/JUCE
  
    # JUCE
    - name: "2/7: Preprocessor Definitions"
      working-directory: ${{runner.workspace}}/phantom/JUCE
      run: perl -i -pe "s/#define JUCE_MODAL_LOOPS_PERMITTED.*/#define JUCE_MODAL_LOOPS_PERMITTED 1/" modules/juce_core/system/juce_PlatformDefs.h

    - name: "3/7: Configuration (JUCE)"
      working-directory: ${{runner.workspace}}/phantom/JUCE
      run: cmake -B bin .

    - name: "4/7: Build (JUCE)"
      working-directory: ${{runner.workspace}}/phantom/JUCE
      run: cmake --build bin

    # Phantom
    - name: "5/7: Precompilation (Phantom)"
      working-directory: ${{runner.workspace}}/phantom
      run: chmod +x ./scripts/precompile.sh && ./scripts/precompile.sh

    - name: "6/7: Configuration (Phantom)"
      working-directory: ${{runner.workspace}}/phantom
      run: cmake -B bin .

    - name: "7/7: Build (Phantom)"
      working-directory: ${{runner.workspace}}/phantom
      run: cmake --build bin --config ${{ env.BUILD_TYPE }} --target Phantom_All

    # Uploading artifacts
    - name: Upload VST3 Artifact (Windows)
      if: ${{ matrix.os == 'windows-latest' }}
      working-directory: ${{runner.workspace}}/phantom
      uses: actions/upload-artifact@v4
      with:
        path: "bin/Phantom_artefacts/Release/VST3/Phantom.vst3/Contents/x86_64-win/Phantom.vst3"

    - name: Upload VST3 Artifact (MacOS)
      if: ${{ matrix.os == 'macos-latest' }}
      working-directory: ${{runner.workspace}}/phantom
      uses: actions/upload-artifact@v4
      with:
        path: "bin/Phantom_artefacts/VST3/Phantom.vst3"
