name: phantom

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest, macos-13]

    env:
      BUILD_TYPE: Release
      CMAKE_BUILD_PARALLEL_LEVEL: 4

    steps:

    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Clone JUCE
      uses: actions/checkout@v2
      with:
        repository: juce-framework/JUCE
        ref: 2f980209cc4091a4490bb1bafc5d530f16834e58
        path: ${{runner.workspace}}/phantom/JUCE
  
    # JUCE
    - name: Configure JUCE
      working-directory: ${{runner.workspace}}/phantom/JUCE
      run: cmake -B bin . -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build JUCE
      working-directory: ${{runner.workspace}}/phantom/JUCE
      run: cmake --build bin --parallel 4

    # Phantom
    - name: Precompile Phantom
      working-directory: ${{runner.workspace}}/phantom
      run: chmod +x ./scripts/precompile.sh && ./scripts/precompile.sh

    - name: Configure Phantom
      working-directory: ${{runner.workspace}}/phantom
      run: cmake -B bin . -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build Phantom
      working-directory: ${{runner.workspace}}/phantom
      run: cmake --build bin --parallel 4 --config ${{ env.BUILD_TYPE }} --target Phantom_All

      # Windows
    - name: Zip Artifact (Windows)
      if: runner.os == 'Windows'
      run: Compress-Archive -Path bin/Phantom_artefacts/Release/VST3/Phantom.vst3/Contents/x86_64-win/Phantom.vst3 -Destination phantom.zip

    - name: Upload Artifact (Windows)
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: phantom-windows
        path: phantom.zip

      # MacOS
    - name: Zip Artifact (MacOS)
      if: runner.os == 'macOS'
      run: zip -r phantom.zip bin/Phantom_artefacts/VST3/Phantom.vst3 bin/Phantom_artefacts/AU/Phantom.component

    - name: Upload Artifact (MacOS)
      if: runner.os == 'macOS'
      uses: actions/upload-artifact@v4
      with:
        name: phantom-macos
        path: phantom.zip
