name: phantom-dev

on:
  push:
    branches:
      - "**"
      - "!main"

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - name: "Preparation"
      uses: actions/checkout@v2

    - name: "1/7 (JUCE): Clone Repository"
      uses: actions/checkout@v2
      with:
        repository: juce-framework/JUCE
        path: ${{runner.workspace}}/phantom/JUCE
  
    # JUCE
    - name: "2/7 (JUCE): Create Build Environment"
      working-directory: ${{runner.workspace}}/phantom/JUCE
      run: cmake -E make_directory ${{runner.workspace}}/phantom/JUCE/bin

    - name: "3/7 (JUCE): Configuration"
      working-directory: ${{runner.workspace}}/phantom/JUCE/bin
      run: cmake ${{runner.workspace}}/phantom/JUCE

    - name: "4/7 (JUCE): Build"
      working-directory: ${{runner.workspace}}/phantom/JUCE/bin
      run: cmake --build .

    # Phantom
    - name: "5/7 (Phantom): Create Build Environment"
      working-directory: ${{runner.workspace}}/phantom
      run: cmake -E make_directory ${{runner.workspace}}/phantom/bin
    
    - name: "6/7 (Phantom): Configuration"
      working-directory: ${{runner.workspace}}/phantom/bin
      run: cmake ${{runner.workspace}}/phantom

    - name: "7/7 (Phantom): Build"
      working-directory: ${{runner.workspace}}/phantom/bin
      run: cmake --build .

  upload:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: "(1/2) Zip"
        uses: papeloto/action-zip@v1
        if: ${{ matrix.os == 'windows-latest' }}
        working-directory: ${{runner.workspace}}/phantom/bin
        with:
          files: Phantom_artefacts/Release/VST3/Phantom.vst3/Contents/x86_64-win/Phantom.vst3
          dest: phantom-win.zip

      - name: "(2/2) Upload"
        uses: actions/upload-artifact@v2
        if: ${{ matrix.os == 'windows-latest' }}
        working-directory: ${{runner.workspace}}/phantom/bin
        with:
          name: phantom-win
          path: phantom/phantom-win.zip

      - name: "(1/2) Zip"
        uses: papeloto/action-zip@v1
        if: ${{ matrix.os == 'macos-latest' }}
        working-directory: ${{runner.workspace}}/phantom/bin
        with:
          files: Phantom_artefacts/VST3/Phantom.vst3 Phantom_artefacts/AU/Phantom.component
          dest: phantom-mac.zip

      - name: "(2/2) Upload"
        uses: actions/upload-artifact@v2
        if: ${{ matrix.os == 'macos-latest' }}
        working-directory: ${{runner.workspace}}/phantom/bin
        with:
          name: phantom-mac
          path: phantom/phantom-mac.zip
