name: phantom

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    env:
      BUILD_TYPE: Release

    steps:
    - name: "Preparation"
      uses: actions/checkout@v2

    - name: "1/6: Clone (JUCE)"
      uses: actions/checkout@v2
      with:
        repository: juce-framework/JUCE
        ref: 2f980209cc4091a4490bb1bafc5d530f16834e58
        path: ${{runner.workspace}}/phantom/JUCE
  
    # JUCE
    - name: "2/6: Configuration (JUCE)"
      working-directory: ${{runner.workspace}}/phantom/JUCE
      run: cmake -B bin .

    - name: "3/6: Build (JUCE)"
      working-directory: ${{runner.workspace}}/phantom/JUCE
      run: cmake --build bin

    # Phantom
    - name: "4/6: Precompilation (Phantom)"
      working-directory: ${{runner.workspace}}/phantom
      run: chmod +x ./scripts/precompile.sh && ./scripts/precompile.sh

    - name: "5/5: Configuration (Phantom)"
      working-directory: ${{runner.workspace}}/phantom
      run: cmake -B bin .

    - name: "6/5: Build (Phantom)"
      working-directory: ${{runner.workspace}}/phantom
      run: cmake --build bin --config ${{ env.BUILD_TYPE }} --target Phantom_All
